// Copyright (c) 2020 RISC Software GmbH
//
// This file was generated by CPACSGen from CPACS XML Schema (c) German Aerospace Center (DLR/SC).
// Do not edit, all changes are lost when files are re-generated.
//
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "CPACSRoot.h"
#include "CTiglError.h"
#include "CTiglLogging.h"
#include "CTiglUIDObject.h"
#include "TixiHelper.h"

namespace tigl
{
namespace generated
{
    CPACSRoot::CPACSRoot()
        : m_mandatoryDouble(0)
        , m_mandatoryInt(0)
    {
    }

    CPACSRoot::~CPACSRoot()
    {
    }

    const CTiglUIDObject* CPACSRoot::GetNextUIDParent() const
    {
        return nullptr;
    }

    CTiglUIDObject* CPACSRoot::GetNextUIDParent()
    {
        return nullptr;
    }

    void CPACSRoot::ReadCPACS(const TixiDocumentHandle& tixiHandle, const std::string& xpath)
    {
        // read element optionalDouble
        if (tixi::TixiCheckElementHasTextContent(tixiHandle, xpath + "/optionalDouble")) {
            m_optionalDouble = tixi::TixiGetElement<double>(tixiHandle, xpath + "/optionalDouble");
        }

        // read element mandatoryDouble
        if (tixi::TixiCheckElementHasTextContent(tixiHandle, xpath + "/mandatoryDouble")) {
            m_mandatoryDouble = tixi::TixiGetElement<double>(tixiHandle, xpath + "/mandatoryDouble");
        }
        else {
            LOG(ERROR) << "Required element mandatoryDouble is missing at xpath " << xpath;
        }

        // read element optionalInt
        if (tixi::TixiCheckElementHasTextContent(tixiHandle, xpath + "/optionalInt")) {
            m_optionalInt = tixi::TixiGetElement<int>(tixiHandle, xpath + "/optionalInt");
        }

        // read element mandatoryInt
        if (tixi::TixiCheckElementHasTextContent(tixiHandle, xpath + "/mandatoryInt")) {
            m_mandatoryInt = tixi::TixiGetElement<int>(tixiHandle, xpath + "/mandatoryInt");
        }
        else {
            LOG(ERROR) << "Required element mandatoryInt is missing at xpath " << xpath;
        }

    }

    void CPACSRoot::WriteCPACS(const TixiDocumentHandle& tixiHandle, const std::string& xpath) const
    {
        const std::vector<std::string> childElemOrder = { "optionalDouble", "mandatoryDouble", "optionalInt", "mandatoryInt" };

        // write element optionalDouble
        if (m_optionalDouble) {
            tixi::TixiCreateSequenceElementIfNotExists(tixiHandle, xpath + "/optionalDouble", childElemOrder);
            tixi::TixiSaveElement(tixiHandle, xpath + "/optionalDouble", *m_optionalDouble);
        }
        else {
            if (tixi::TixiCheckElement(tixiHandle, xpath + "/optionalDouble")) {
                tixi::TixiRemoveElement(tixiHandle, xpath + "/optionalDouble");
            }
        }

        // write element mandatoryDouble
        tixi::TixiCreateSequenceElementIfNotExists(tixiHandle, xpath + "/mandatoryDouble", childElemOrder);
        tixi::TixiSaveElement(tixiHandle, xpath + "/mandatoryDouble", m_mandatoryDouble);

        // write element optionalInt
        if (m_optionalInt) {
            tixi::TixiCreateSequenceElementIfNotExists(tixiHandle, xpath + "/optionalInt", childElemOrder);
            tixi::TixiSaveElement(tixiHandle, xpath + "/optionalInt", *m_optionalInt);
        }
        else {
            if (tixi::TixiCheckElement(tixiHandle, xpath + "/optionalInt")) {
                tixi::TixiRemoveElement(tixiHandle, xpath + "/optionalInt");
            }
        }

        // write element mandatoryInt
        tixi::TixiCreateSequenceElementIfNotExists(tixiHandle, xpath + "/mandatoryInt", childElemOrder);
        tixi::TixiSaveElement(tixiHandle, xpath + "/mandatoryInt", m_mandatoryInt);

    }

    const boost::optional<double>& CPACSRoot::GetOptionalDouble() const
    {
        return m_optionalDouble;
    }

    void CPACSRoot::SetOptionalDouble(const boost::optional<double>& value)
    {
        m_optionalDouble = value;
    }

    const double& CPACSRoot::GetMandatoryDouble() const
    {
        return m_mandatoryDouble;
    }

    void CPACSRoot::SetMandatoryDouble(const double& value)
    {
        m_mandatoryDouble = value;
    }

    const boost::optional<int>& CPACSRoot::GetOptionalInt() const
    {
        return m_optionalInt;
    }

    void CPACSRoot::SetOptionalInt(const boost::optional<int>& value)
    {
        m_optionalInt = value;
    }

    const int& CPACSRoot::GetMandatoryInt() const
    {
        return m_mandatoryInt;
    }

    void CPACSRoot::SetMandatoryInt(const int& value)
    {
        m_mandatoryInt = value;
    }

} // namespace generated
} // namespace tigl
